/* Category metadata. Order here is the order shown on the home page. */
window.CATEGORIES = [
  { id:'puzzles',     name:'Puzzles, Tricks & Brain Skills',
    blurb:'Cubes, cards, memory systems and mental arithmetic — the skills that look like magic and are mostly method.' },
  { id:'dexterity',   name:'Coordination & Dexterity',
    blurb:'Juggling, spinning, shuffling. Pure repetition skills where your hands learn faster than your head.' },
  { id:'outdoors',    name:'Outdoor & Survival Skills',
    blurb:'Fire, knots, shelter, water and navigation — the classic competences, each with a clear pass/fail.' },
  { id:'physical',    name:'Physical Skills',
    blurb:'Handstands, rope climbs, first pull-ups and fight-sport fundamentals you can train in a corner of a room.' },
  { id:'music',       name:'Music & Rhythm',
    blurb:'You will not become a musician in three weeks, but you can become genuinely good at one narrow musical thing.' },
  { id:'making',      name:'Making & Repair Skills',
    blurb:'Sewing, sharpening, soldering, bikes, cars and drywall — the stop-paying-someone-else tier of adulthood.' },
  { id:'cooking',     name:'Cooking & Food Skills',
    blurb:'Knife work, dough, sauces and protein cookery. Practise these and you eat the homework.' },
  { id:'social',      name:'Social & Performance Skills',
    blurb:'Stories, speeches, names, listening and dancing — trainable skills that most people leave to chance.' },
  { id:'observation', name:'Observation & Awareness Skills',
    blurb:'Learn to read the sky, the trees, the birds and the map. The world gets noisier in a good way.' },
  { id:'creative',    name:'Creative Skills',
    blurb:'Drawing, lettering, folding, carving, shooting and editing — output-based skills with visible weekly progress.' },
  { id:'technology',  name:'Technology Skills',
    blurb:'Typing, the command line, a first website, spreadsheets, Git and sane security hygiene.' },
  { id:'navigation',  name:'Navigation & Travel Skills',
    blurb:'Maps, compasses, transit systems and carry-on packing: how to arrive without a blue dot to follow.' },
  { id:'precision',   name:'Precision & Party Skills',
    blurb:'The best effort-to-impressiveness ratio on the whole list. Cards, cues, darts, whips and kendama.' },
  { id:'oldschool',   name:'Old-School Practical Skills',
    blurb:'Shorthand, slide rules, wax seals, ties, shoeshine and cordage — analogue competence, quietly satisfying.' }
];
