/* Fetches the Google Fonts used by the site and writes css/fonts.css with each
   face inlined as a base64 data URI. Run this only when the font list changes:
   the generated file is committed, so neither the site nor the published
   artifact depends on a font CDN at view time.
   Run: node build-fonts.js */
const { execFileSync } = require('child_process');
const fs = require('fs');

const CSS_URL = 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wght@400..700&family=Instrument+Serif:ital@0;1&display=swap';
// A modern UA is what makes Google serve woff2 rather than legacy formats.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const KEEP = ['latin', 'latin-ext'];       // the subsets this content actually needs

const curl = (url, binary) =>
  execFileSync('curl', ['-sS', '-A', UA, url], { maxBuffer: 1 << 26, encoding: binary ? 'buffer' : 'utf8' });

const css = curl(CSS_URL);
const blocks = css.split('/*').slice(1);   // Google prefixes each block with a /* subset */ comment
let out = '/* Generated by build-fonts.js — do not edit. Google Fonts, inlined. */\n';
let kept = 0, bytes = 0;

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf('*/')).trim();
  if (!KEEP.includes(subset)) continue;
  const block = raw.slice(raw.indexOf('*/') + 2);
  const url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
  if (!url) continue;
  const data = curl(url, true);
  bytes += data.length;
  kept++;
  out += '/* ' + subset + ' */\n' + block.replace(
    /url\(https:[^)]+\.woff2\)/,
    "url(data:font/woff2;base64," + data.toString('base64') + ")"
  ).trim() + '\n';
}

fs.writeFileSync('css/fonts.css', out);
console.log('css/fonts.css — ' + kept + ' faces, ' + (bytes / 1024).toFixed(0) + ' KB of woff2, ' +
            (out.length / 1024).toFixed(0) + ' KB encoded');
