/* Compiles data/ into js/skills.js, the single file the page loads.
 *
 * The site has no build step at request time and no server: it is static files
 * served from a subdirectory. A <script src> cannot load JSON, and fetching 423
 * files at runtime would cost hundreds of round trips, break opening index.html
 * over file://, and break the single-file bundle. So the JSON is the source you
 * edit and js/skills.js is the compiled artefact, committed alongside it.
 *
 *   node build-data.js          rebuild js/skills.js
 *   node build-data.js --check  verify it is up to date (exit 1 if stale)
 *
 * Layout:
 *   data/categories.json     the categories, in home-page order
 *   data/<cat>/index.json    that category's skill ids, in display order
 *   data/<cat>/<id>.json     one skill
 */
const fs = require('fs');
const path = require('path');

const DATA = path.join(__dirname, 'data');
const OUT = path.join(__dirname, 'js', 'skills.js');
const REQUIRED = ['id', 'name', 'time', 'level', 'blurb', 'gear', 'steps', 'tips', 'proof'];
const LEVELS = ['Easy', 'Moderate', 'Hard'];

const readJSON = f => JSON.parse(fs.readFileSync(f, 'utf8'));
const problems = [];
const fail = (where, msg) => problems.push(where + ': ' + msg);

const categories = readJSON(path.join(DATA, 'categories.json'));
const seen = new Set();
const skills = [];

for (const cat of categories) {
  for (const k of ['id', 'name', 'blurb']) {
    if (!cat[k]) fail('categories.json', 'category missing ' + k);
  }
  const dir = path.join(DATA, cat.id);
  if (!fs.existsSync(dir)) { fail(cat.id, 'no folder for this category'); continue; }

  const order = readJSON(path.join(dir, 'index.json'));
  const onDisk = fs.readdirSync(dir)
    .filter(f => f.endsWith('.json') && f !== 'index.json')
    .map(f => f.slice(0, -5));

  // Index and folder must agree exactly, so a typo or a forgotten index entry
  // fails the build instead of silently dropping a skill from the site.
  onDisk.filter(id => !order.includes(id))
    .forEach(id => fail(cat.id, id + '.json exists but is not listed in index.json'));
  order.filter(id => !onDisk.includes(id))
    .forEach(id => fail(cat.id, 'index.json lists ' + id + ' but ' + id + '.json is missing'));

  for (const id of order) {
    if (!onDisk.includes(id)) continue;
    const skill = readJSON(path.join(dir, id + '.json'));
    const where = cat.id + '/' + id + '.json';

    if (skill.id !== id) fail(where, 'id field is "' + skill.id + '" but the filename says "' + id + '"');
    if (seen.has(id)) fail(where, 'duplicate skill id');
    seen.add(id);
    if ('cat' in skill) fail(where, 'remove the "cat" field — the folder defines the category');
    REQUIRED.forEach(k => {
      const v = skill[k];
      if (v === undefined || v === '' || (Array.isArray(v) && !v.length)) fail(where, 'missing ' + k);
    });
    if (skill.level && !LEVELS.includes(skill.level)) {
      fail(where, 'level "' + skill.level + '" is not one of ' + LEVELS.join(', '));
    }
    skills.push(Object.assign({ id: skill.id, cat: cat.id }, skill));
  }
}

if (problems.length) {
  console.error('data problems:\n  ' + problems.join('\n  '));
  process.exit(1);
}

const banner = '/* Generated by build-data.js from data/ — do not edit.\n' +
               '   Edit the JSON under data/ and re-run: node build-data.js */\n';
const body = banner +
  'window.CATEGORIES = ' + JSON.stringify(categories, null, 2) + ';\n' +
  'window.SKILLS = ' + JSON.stringify(skills, null, 2) + ';\n';

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error('js/skills.js is stale — run: node build-data.js');
    process.exit(1);
  }
  console.log('js/skills.js is up to date (' + skills.length + ' skills, ' + categories.length + ' categories)');
} else {
  fs.writeFileSync(OUT, body);
  console.log('js/skills.js — ' + skills.length + ' skills, ' + categories.length + ' categories, ' +
              (body.length / 1024).toFixed(0) + ' KB');
}
